version: '3'
services:
  rag:
    container_name: rag
    build: .
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
      - "8000:8000"
    volumes:
      - "./app:/app"

